import NavBar from "@/components/NavBar.tsx";
import useTextDirection from "@/hooks/useTextDirection.tsx";
import type { Metadata } from "next";
import {
  El_Messiri as Arabic,
  Gabarito as English,
} from "next/font/google";
import { notFound } from "next/navigation";
import MobileNav from "@/components/MobileNav.tsx";
import "./globals.css";
import { Providers } from "./providers.tsx";
import { NextIntlClientProvider, useMessages } from "next-intl";

const arabic = Arabic({
  subsets: ["latin"],
  weight: "400",
});

const english = English({
  subsets: ["latin"],
  weight: "400",
});

const locales = ["en", "ar"];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: any;
}) {
  if (!locales.includes(locale as any)) notFound();
  const direction = useTextDirection(locale);
  const messages = useMessages();

  return (
    <html lang={locale} dir={direction}>
      <body
        className={direction === "rtl" ? arabic.className : english.className}
      >
        <Providers>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <NavBar />
            <MobileNav />
            {children}
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
